<?php

// Language definitions used in all admin files
$lang_admin_bans = array(

'Ban advanced'					=>	'Avancerade bannlysningar',
'Ban advanced heading'			=>	'Bannbullor på användarnamn med IP och epost, eller bara IP, epost eller bådadera',
'Ban criteria legend'			=>	'Kriteria för bannlysning',
'Ban settings legend'			=>	'Inställningar för bannlysning',
'Ban IP warning'				=>	'<strong>Varning!</strong> Du måste vara försiktig när du bannlyser IP-spann, eftersom det kan hända att du i ett svep förpassar flera personer till utanförskap. Även oförtjänt!',
'Current ban head'				=>	'Bannlyst av %s',
'Username'						=>	'Användarnamn:',
'Username to ban label'			=>	'Användarnamn att bannlysa',
'Ban creator'					=>	'Bannlyst av',
'IP-addresses to ban label'		=>	'IP-adresser att bannlysa',
'IP-addresses help'				=>	'IP-adressen eller -adresserna du vill bannlysa (t.ex. 150.11.110.1 eller 150.11.110). Separera med mellanslag. Om en IP-adress redan är ifylld, så är detta användarens senaste kända IP-adress.',
'IP-addresses help stats'		=>	'Klicka på följande länk för att se IP-statistik för användaren: ',
'IP-addresses help link'		=>	'IP-statistik för användare',
'E-mail/domain to ban label'	=>	'Epost-adress eller -domän att bannlysa',
'E-mail/domain help'			=>	'Epost-adressen eller -domänen du vill bannlysa (t.ex. fuling@example.com eller example.com). Se "Tillåt registrering med bannlysta epost-adresser" under Inställningar/Registrering för mera information.',
'Ban message label'				=>	'Meddelande om bannlysning',
'Ban message help'				=>	'Visas för den bannlysta användaren när han eller hon besöker plankan',
'Expire date label'				=>	'Bannlysningens bäst före-datum',
'Expire date help'				=>	'Bara Sisyfos är fast för evigt. Ange när bannlysningen ruttnar bort (format: ÅÅÅÅ-MM-DD) och användaren får vara med igen. Lämna fältet tomt för att kräva att bannlysningen lyfts manuellt.',
'Expires'						=>	'Går ut:',
'Message'						=>	'Meddelande:',
'New ban heading'				=>	'Bannlys specifikt användarnamn',
'New ban legend'				=>	'Ny bannlysning',
'Advanced ban info'				=>	'På nästa sida kan du fylla i en IP-adress och epost-adress. Om du vill bannlysa endast en viss IP-adress eller ett visst IP-spann, eller bara en viss epost-adress, så lämnar du fältet för användarnamn på den här sidan tomt.',
'Existing bans heading'			=>	'Ändra eller lyft existerande bannbullor',
'Add ban'						=>	'Skapa bannlysning',
'Save ban'						=>	'Spara bannlysning',
'E-mail'						=>	'Epost:',
'IP-ranges'						=>	'IP/IP-spann:',
'Reason'						=>	'Orsak',
'No bans'						=>	'Inga bannbullor att lista.',
'Edit ban'						=>	'Ändra bannlysning',
'Remove ban'					=>	'Lyft bannlysning',
'Edit or remove'				=>	'%s eller %s',
'Ban removed'					=>	'Bannlysningen lyftes.',
'Ban added'						=>	'Bannlysningen genomfördes.',
'Ban edited'					=>	'Bannlysningen ändrades.',
'No user id message'			=>	'Ingen användare med ett sådant ID finns registrerad.',
'No user username message'		=>	'Ingen användare med ett sådant användarnamn finns registrerad. Om du vill lägga en bannlysning som inte är knuten till något specifikt användarnamn kan du lämna fältet för användarnamn tomt.',
'User is admin message'			=>	'Den här användaren är administratör och har påvlig status. Man kan inte bannlysa en påve. Flytta påven i fråga till någon annan grupp först.',
'Must enter message'			=>	'Du måste ange åtminstone någotdera av följande: användarnamn, IP-adress eller epost-adress.',
'Invalid IP message'			=>	'Du angav en ogiltig IP-adress eller ett ogiltigt IP-spann.',
'Can\'t ban guest user'			=>	'Gäst-användaren kan inte bannlysas.',
'Invalid e-mail message'		=>	'Epost-adressen (t.ex. user@example.com) eller biten av en epost-adress (t.ex. example.com) du angav är ogiltig.',
'Invalid expire message'		=>	'Du angav ett ogiltigt bäst före-datum. Formatet måste vara ÅÅÅÅ-MM-DD och ligga åtminstone en dag in i framtiden.',


);
