<?php

// Language definitions used in all admin files
$lang_admin_users = array(

// admin_users
'Search head'					=>	'Sök använd',
'User search head'				=>	'Ange ett eller fler kriteria. Använd jokertecknet <strong>*</strong> för att söka på delar av användarnamn.',
'Searches personal legend'		=>	'Personlig information',
'Username label'				=>	'Användarnamn',
'Title label'					=>	'Titel',
'Real name label'				=>	'Verkligt namn',
'Location label'				=>	'Plats',
'Signature label'				=>	'Signatur',
'Admin note label'				=>	'Administratörsanteckning',
'Searches contact legend'		=>	'Kontaktinformation',
'E-mail address label'			=>	'Epostadress',
'Website label'					=>	'Webbplats',
'Searches activity legend'		=>	'Aktivitetsnivå',
'More posts label'				=>	'Fler inlägg än',
'Less posts label'				=>	'Färre inlägg än',
'Number of posts help'			=>	'(Antal inlägg)',
'Last post after label'			=>	'Senaste inlägget är nyare än',
'Last post before label'		=>	'Senaste inlägget är äldre än',
'Registered after label'		=>	'Registrerad senare än',
'Registered before label'		=>	'Registrerad tidigare än',
'Date format help'				=>	'[ ååå-mm-dd tt:mm:ss ]',
'Jabber label'					=>	'Jabber',
'ICQ label'						=>	'ICQ',
'MSN Messenger label'			=>	'MSN Messenger',
'AOL IM label'					=>	'AOL IM',
'Yahoo Messenger label'			=>	'Yahoo! Messenger',
'User results head'				=>	'Sortera sökresultat',
'User results legend'			=>	'Sökresultat',
'Order by label'				=>	'Sortera efter',
'Sort order label'				=>	'Sorteringsordning',
'User group label'				=>	'Användargrupp',
'IP search head'				=>	'Hitta en specifik IP-adress i inläggsdatabasen',
'IP search legend'				=>	'Ange IP-adress att leta efter',
'IP address label'				=>	'IP-adress',
'User information'				=>	'Användarinformation',
'IP address'					=>	'IP-adress',
'Username'						=>	'Användarnamn',
'E-mail'						=>	'Epost',
'Admin note'					=>	'Administratörsanteckning',

'Invalid IP address'			=>	'Du angav en ogiltig IP-adress.',
'Users matching criteria'		=>	'Resultat som matchar sökkriterierna',
'User IP stats'					=>	'IP-statistik för användare',
'IP matching criteria'			=>	'Resultat som matchar IP-adress',
'Users found'					=>	'Användare funna [ %s ]',
'IP addresses found'			=>	'IP-adress funnen [ %s ]',
'Moderate users'				=>	'Moderera användare',
'Submit search'					=>	'Sök',
'Not verified'					=>	'Ej bekräftad',
'Registered'					=>	'Registrerad',
'Last post'						=>	'Senaste inlägg',
'Ascending'						=>	'Stigande',
'Descending'					=>	'Fallande',
'All groups'					=>	'Alla grupper',
'Unverified users'				=>	'Ej bekräftade användare',
'Non numeric value message'		=>	'Du angav ett icke-numeriskt värde i en numerisk kolumn',
'Invalid date/time message'		=>	'Du angav ett ogiltigt datum eller klockslag',
'No search terms message'		=>	'Du angav inga sökkriteria.',
'Delete users'					=>	'Ta bort användare',
'Delete warning'				=>	'<strong>Varning!</strong> Borttagna användare och inlägg kan inte återställas. Om du väljer att inte ta bort inlägg användarna ifråga publicerat, så kan inläggen därefter enbart tas bort manuellt.',
'Delete posts legend'			=>	'Då kan välja att ta bort inlägg de här användarna publicerat',
'Confirm delete'				=>	'Bekräfta borttagning',
'Delete posts'					=>	'Ta bort inlägg',
'Delete posts label'			=>	'Kryssa för detta för att ta bort alla trådar och inlägg som användarna ifråga publicerat.',
'Users deleted'					=>	'Användarna togs bort.',
'Ban'							=>	'Bannlys',
'Ban users'						=>	'Bannlys användare',
'Change group'					=>	'Ändra grupp',
'Delete admin message'			=>	'Administratörer kan inte tas bort. För att ta bort en administratör måste du först flytta honom eller henne till en annan användargrupp.',
'Ban admin message'				=>	'En av de valda användarna är administratör och kan inte bannlysas. Om du vill bannlysa en administratör måste du först flytta honom eller henne till en annan användargrupp.',
'Users banned'					=>	'Användarna bannlystes.',
'Mass ban info'					=>	'Du kan skriva ett meddelande som visas för bannlysta användare, samt ett en tidpunkt då bannlysningen automatiskt kommer att upphöra.',
'Ban settings legend'			=> 	'Bannlys användare',
'Change group head'				=>	'Flytta valda användare till ny grupp',
'User groups updated'			=>	'Användargrupperna uppdaterades.',
'Move users legend'				=>	'Flytta användare',
'No users selected'				=>	'Inga användare valda',
'Move users to label'			=>	'Flytta användare till grupp',

// admin_users tables
'Username column'				=>	'Användarnamn — Epost — Administratörsanteckning',
'Title column'					=>	'Titel — Status',
'Posts'							=>	'Inlägg',
'Actions'						=>	'Handling(ar)',
'View IP stats'					=>	'Visa IP-statistik',
'Show posts'					=>	'Visa inlägg',
'Last used'						=>	'Senast använd',
'Times found'					=>	'Antal exemplar',
'Find more users'				=>	'Hitta andra användare med samma IP-adress',
'No posts by user'				=>	'För närvarande finns inga inlägg publicerade av den användaren på brädan.',
'Guest'							=>	'Gäst',
'Cannot find IP'				=>	'Angiven IP-adress hittades inte i databasen.',
'Not verified'					=>	'Ej bekräftad',
'No match'						=>	'Ingen träff',
'User search results'			=>	'Sökresultat'

);
