<?php

// Language definitions used in all admin files
$lang_admin_groups = array(

// admin_groups
'Group settings heading'		=>	'Gruppens förvalda åtkomsträttigheter, som gäller om inga särskilda rättigheter anges.',
'Group title label'				=>	'Gruppens namn',
'User title label'				=>	'Användares titel',
'Group title head'				=>	'Grupp',
'Group title legend'			=>	'Ange titlar',
'Group perms head'				=>	'Åtkomsträttigheter',
'Group flood head'				=>	'Inställningar för skydd mot masspostningar',
'User title help'				=>	'Denna titel kommer användas i stället för eventuella grader som användare i gruppen uppnått. Lämna fältet tomt för att i stället visa de enskilda användarnas titlar.',
'Remove group legend'			=>	'Ta bort grupp',
'Permissions'					=>	'Åtkomsträttigheter',
'Moderation'					=>	'Moderering',
'Allow moderate label'			=>	'Ge användare rätt att moderera.',
'Allow mod edit profiles label'	=>	'Ge moderatorer rätt att ändra användarprofiler.',
'Allow mod edit username label'	=>	'Ge moderatorer rätt att byta namn på användare',
'Allow mod change pass label'	=>	'Ge moderatorer rätt att ändra användares lösenord',
'Allow mod bans label'			=>	'Ge moderatorer rätt att bannlysa användare',
'Allow read board label'		=>	'Ge användare rätt att se brädan.',
'Allow read board help'			=>	'Den här inställningen omfattar varje aspekt av brädan, och har högre prioritet än motsvarande inställning för enskilda fora. Om rätten att se brädan fråntas användare så kan de inte göra något mer än att logga in, logga ut samt registrera konton.',
'Allow view users label'		=>	'Ge användare rätt att visa användarlistan och användarprofiler.',
'Allow post replies label'		=>	'Ge användare rätt att skriva trådsvar.',
'Allow post topics label'		=>	'Ge användare rätt att skapa nya trådar.',
'Allow edit posts label'		=>	'Ge användare rätt att ändra sina egna inlägg.',
'Allow delete posts label'		=>	'Ge användare rätt att ta bort sina egna inlägg.',
'Allow delete topics label'		=>	'Ge användare rätt att ta bort sina egna trådar (och därmed samtliga trådsvar).',
'Allow set user title label'	=>	'Ge användare rätt att själva välja titel.',
'Allow use search label'		=>	'Ge användare rätt att använda sökfunktionen.',
'Allow search users label'		=>	'Ge användare rätt att genomföra fritextsökningar på användarlistan.',
'Allow send email label'		=>	'Ge användare rätt att skicka epost till andra användare.',
'Restrictions'					=>	'Begränsningar',
'Mod permissions'				=>	'Moderator-rättigheter',
'User permissions'				=>	'Användar-rättigheter',
'Flood interval label'			=>	'Intervall mellan inlägg',
'Flood interval help'			=>	'Hur ofta, i antal sekunder, som användare i den här gruppen tillåts skriva inlägg. Ange 0 för att stänga av begränsningen.',
'Search interval label'			=>	'Intervall mellan sökningar',
'Search interval help'			=>	'Hur ofta, i antal sekunder, som användare i den här gruppen tillåts genomföra sökningar. Ange 0 för att stänga av begränsningen.',
'Email flood interval label'	=>	'Intervall mellan epost',
'Email flood interval help'		=>	'Hur ofta, i antal sekunder, som användare i den här gruppen tillåts skicka epost via forumet. Ange 0 för att stänga av begränsningen.',
'Allow moderate help'			=>	'För att en användare i den här gruppen ska kunna ha moderator-rättigheter måste han eller hon tilldelas minst ett forum att moderera. Detta kan görs från sidan för administration av användare, som går att komma åt via användarens profil.',
'Remove group'					=>	'Ta bort den här gruppen',
'Edit group'					=>	'Ändra den här gruppen',
'default'						=>	'(förvald)',
'Cannot remove group'			=>	'Den här gruppen kan inte tas bort',
'Cannot remove default'			=>	'För att ta bort den här gruppen måste en ny grupp anges som förval.',
'Remove group head'				=>	'Ta bort gruppen "%s" som innehåller %s användare',
'Remove group help'				=>	'(Flytta gruppens användare till denna grupp)',
'Move users to'					=>	'Flytta användare till',
'Cannot remove default group'	=>	'En förvald grupp kan inte tas bort. För att ta bort den här gruppen måste först en annan anges som förval.',
'Add group heading'				=>	'Skapa ny grupp (som ärver åtkomsträttigheterna hos den befintliga grupp som den baseras på)',
'Add group legend'				=>	'Skapa ny grupp',
'Edit group heading'			=>	'Ändra befintlig grupp',
'Base new group label'			=>	'Basera ny grupp på',
'Add group'						=>	'Skapa ny grupp',
'Default group heading'			=>	'Förvald grupp för nya användare (grupperna administrerings- och modereringsrättigheter kan av säkerhetsskäl inte väljas)',
'Default group legend'			=>	'Ange förvald grupp för nya användare',
'Default group label'			=>	'Förvald grupp',
'Set default'					=>	'Ange förvald grupp',
'Existing groups heading'		=>	'Befintliga grupper',
'Existing groups intro'			=>	'Grupperna Gäster och Administratörer kan inte tas bort. Det går dock att redigera dem. Notera dock att vissa alternativ inte finns tillgängliga (t.ex. "ändra inlägg" för gäster). Administratörer har alltid fulla rättigheter, till skillnad från pizzerior.',
'Group removed'					=>	'Gruppen togs bort',
'Default group set'				=>	'Gruppen angavs som förval',
'Group added'					=>	'Gruppen lades till.',
'Group edited'					=>	'Gruppen ändrades.',
'Update group'					=>	'Uppdatera grupp',
'Must enter group message'		=>	'Gruppen måste ha ett namn.',
'Already a group message'		=>	'En grupp med namnet <strong>"%s"</strong> finns redan.',
'Moderator default group'		=>	'Den här gruppen är förvald för nya användare och kan därför inte ges rätt att moderera.',

);
