<?php

// Language definitions used in admin-categories
$lang_admin_forums = array(

'Edit forum head'				=>	'Ändra forum: %s',
'Edit or delete'				=>	'%s eller %s',
'Edit'							=>	'Ändra',
'Delete'						=>	'Ta bort',
'Forum name'					=>	'Forumets namn',
'Position label'				=>	'Position',
'Delete forum'					=>	'Ta bort forum',
'Delete forum warning'			=>	'<strong>Varning!</strong> När ett forum tas bort försvinner även alla inlägg i det borttagna forumet!',
'Edit forum'					=>	'Ändra forum',
'Edit forum details legend'		=>	'Forumdetaljer',
'Category assignment'			=>	'Placera i kategori',
'Forums in category'			=>	'Forums i kategori: %s',
'Edit forum perms legend'		=>	'Åtkomsträttigheter för forum (ej förvalda rättigheter är märkta med "(Ä)"',
'Forum name label'				=>	'Forumets namn',
'Position label'				=>	'Position',
'Add to category label'			=>	'Placera i kategori',
'Forum description'				=>	'Beskrivning',
'Forum description help'		=>	'(Det går att använda HTML i beskrivningen)',
'Sort topics by'				=>	'Sortera ämnen efter',
'Sort last post'				=>	'Senaste inlägg',
'Sort topic start'				=>	'Trådstart',
'Redirect URL'					=>	'Omdirigerings-URL',
'Only for empty forums'			=>	'Endast för tomma fora',
'Edit forums head'				=>	'Ändra eller ta bort forumpositioner',
'Edit forum details head'		=>	'Ändra forumdetaljer',
'Edit forum perms head'			=>	'Ändra åtkomsträttigheter för forum',
'Post replies'					=>	'Skapa inlägg',
'Post topics'					=>	'Skapa trådar',
'User groups'					=>	'Användargrupper',
'Confirm delete forum'			=>	'Du är på väg att ta bort forumet "%s"',
'Forum perms read info'			=>	'Åtkomsträttigheten "Visa forum" kommer stängas av om gruppen ifråga saknar åtkomsträttigheter att se brädan.',
'Forum perms redirect info'		=>	'Detta är ett omdirigeringsforum. Endast åtkomsträttigheten "Visa forum" är möjlig att ändra.',
'Forum perms restore info'		=>	'Frövalda åtkomsträttigheter kan återställas med hjälp av knappen "Fabriksåterställning" nedan.',
'Forum perms groups info'		=>	'Rättigheter som inte stämmer överens med dem som valts i %s märks nedan med "(Ä)".',
'Forum perms admins info'		=>	'Forumadministratörer har alltid full åtkomsträttighet, vilket inte går att ändra på.',
'Not default'					=>	'(Ä)',
'Read forum'					=>	'Visa&#160;forum',
'Restore defaults'				=>	'Fabriksåterställning',
'Add forum'						=>	'Lägg till forum',
'Add forum head'				=>	'Skapa forum i vald kategori på angiven position',
'Add forum legend'				=>	'Lägg till forum',
'Add to category'				=>	'Placera i kategori',
'Update positions'				=>	'Uppdatera positioner',
'Forum added'					=>	'Forumet lades till.',
'Forum deleted'					=>	'Forumet togs bort.',
'Forums updated'				=>	'Forumen uppdaterades.',
'Forum updated'					=>	'Forumet uppdaterades.',
'Permissions reverted'			=>	'Åtkomsträttigheterna återställdes till förval.',
'Must enter forum message'		=>	'Du måste ange ett forumnamn.You must enter a forum name.',

);
