<?php

// Language definitions used in viewforum.php
$lang_forum = array(

'Forum subtitle'			=>	'%1$s i detta forum med detaljer som %2$s.',
'Search subtitle'			=>	'%1$s funna med detaljer som %2$s.',
'Topics'					=>	'Trådar',
'topics'					=>	'trådar',
'Reply'						=>	'Svar',
'Replies'					=>	'Svar',
'Forum'						=>	'Forum',
'reply'						=>	'svar',
'replies'					=>	'svar',
'View'						=>	'Visning',
'Views'						=>	'Visningar',
'views'						=>	'visningar',
'view'						=>	'visning',
'Last post'					=>	'Senaste inlägg',
'last post'					=>	'senaste inlägg',
'Select topic'				=>	'Välj tråd: %s.',
'No replies info'			=>	'Ingen information om svar',
'No views info'				=>	'Ingen information om visningar',
'No lastpost info'			=>	'Ingen information om senaste inlägg',
'by poster'					=>	'av %s',
'Item status'				=>	'%s:',
'Topic starter'				=>	'av <cite>%s</cite>',
'New posts'					=>	'Nya inlägg',
'Topic navigation'			=>	'( %s )',
'Location'					=>	'Fanns i forum: %s',
'Pages'						=>	'Sidor',
'Post topic'				=>	'Skapa ny tråd',
'Login to post'				=>	'Du måste %1$s eller %2$s för att skapa en ny tråd',
'No permission'				=>	'Du saknar rätt att skapa nya trådar',
'Moved'						=>	'Flyttad',
'Sticky'					=>	'Klistrad',
'Closed'					=>	'Stängd',
'Empty forum'				=>	'Tomt forum',
'No topics'					=>	'Inga trådar har skapats',
'First topic nag'			=>	'Bli först att skapa en tråd i detta forum.',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'Permalänk till detta forum.',
'Forum options'				=>	'Forum-inställningar',
'Moderate forum'			=>	'Moderera forum',
'Mark forum read'			=>	'Märk forum som läst',
'RSS forum feed'			=>	'RSS-flöde för forum',
'New posts info'			=>	'Hoppa till det första nya inlägget sedan ditt senaste besök.',
'Unsubscribe'				=>	'Sluta prenumerera via epost',
'Subscribe'					=>	'Prenumerera via epost',
'Subscribe info'			=>	'Få på epost-meddelanden om nya trådar.',

);
