<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'No search permission'		=>	'Du saknar tillåtelse att använda sökfunktionen.',
'Search heading'			=>	'Sök i forumen efter angivna kriteria',
'Search flood'				=>	'Åtminstone %s sekunder måste förflyta mellan sökningar. Vänta ett lämpligt slag och försök sedan igen.',
'Search legend'				=>	'Sök-kriteria',
'Results legend'			=>	'Sökresultat',
'Keywords info'				=>	'Du kan söka efter enstaka eller flera ord separerade med mellanslag.',
'Refine info'				=>	'Använd nyckelorden <strong>AND</strong>, <strong>OR</strong> och <strong>NOT</strong> för att ge din sökning lämplig boolesk touch.',
'Wildcard info'				=>	'Vilda västern-sökningar kan genomföras med hjälp av asterisker, alltså <strong>*</strong>. Detta fungerar både för sökord och användarnamn.',
'Forum default info'		=>	'Om inget annat anges kommer sökningen att köras i samtliga forum. Vill du vara mera specifik kan du ange vilka forum som ska genomsökas.',
'Forum require info'		=>	'Du kan genomsöka ett eller flera forum. Du <strong>måste</strong> dock söka i minst ett forum, eftersom den tomma mängden per definition är tom.',
'Keyword search'			=>	'Nyckelord och sökord',
'Author search'				=>	'Författarens användarnamn',
'Forum search'				=>	'Ange forum att genomsöka',
'Forum search default'		=>	'Om inga forum anges kommer sökningen köras i samtliga.',
'Forum search require'		=>	'Du måste välja åtminstone ett forum att genomsöka.',
'Sort by'					=>	'Sortera resutat efter',
'Sort order'				=>	'Sortering av resultat',
'Sort by post time'			=>	'Tidpunkt',
'Sort by author'			=>	'Författare',
'Sort by subject'			=>	'Ämne',
'Sort by forum'				=>	'Forum',
'Ascending'					=>	'Stigande',
'Descending'				=>	'Fallande',
'Display results'			=>	'Visa resultat',
'Show as topics'			=>	'Som trådar',
'Show as posts'				=>	'Som inlägg',
'Submit search'				=>	'Sök',
'User defined search'		=>	'Anpassad sökning',
'Advanced search'			=>	'Avancerad sökning',
'Search in'					=>	'Sök i',
'Message and subject'		=>	'Meddelandetext och trådämne',
'Message only'				=>	'Endast meddelandetext',
'Topic only'				=>	'Endast trådämne',

// Results
'Search results'			=>	'Sökresultat',
'Topics with new'			=>	'Trådar med nya inlägg',
'All Topics'				=>	'Visa alla trådar',
'Recently active topics'	=>	'Nyligen aktiva trådar',
'Unanswered topics'			=>	'Icke besvarade trådar',
'Subscriptions'				=>	'Prenumerationer',
'Forum subscriptions'		=>	'Prenumerationer på forum',
'Forums found'				=>	'Funna forum',
'Topics found'				=>	'Funna trådar',
'Posts found'				=>	'Funna inlägg',
'Topics by'					=>	'Trådar efter %s',
'Posts by'					=>	'Inlägg efter %s',
'Topics by user'			=>	'Trådar av den här användaren',
'Posts by user'				=>	'Inlägg av den här användaren',
'Perform new search'		=>	'Kör en ny sökning',
'Search options'			=>	'Sökalternativ',
'Posted in'					=>	'Postad i ',
'No terms'					=>	'Du har vare sig angivit sökord eller författare att söka inlägg efter. Sådana sökningar godtas inte.',
'No hits'					=>	'Ingenting passade dina sök-kriteria.',
'No user posts'				=>	'Den användaren har inte skrivit några inlägg i forumet.',
'No user topics'			=>	'Den användaren har inte skapat några trådar i forumet.',
'No subscriptions'			=>	'Det finns inga prenumerationer på trådar.',
'No forum subscriptions'	=>	'Det finns inga prenumerationer på forum.',
'No new posts'				=>	'Det finns inga trådar med nya inlägg sedan ditt senaste besök.',
'No recent posts'			=>	'Inga inlägg har publicerats på sistone.',
'No unanswered'				=>	'Det finns inga obesvarade inlägg i forumet.',
'Go to post'				=>	'Hoppa till inlägg',
'Go to forum'				=>	'Hoppa till forum',
'Go to topic'				=>	'Hoppa till tråd',
'Go to profile'				=>	'Hoppa till profilsida för %s'

);
